# Generated by Django 4.1.7 on 2023-04-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(default='AUTHOR', max_length=30, unique=True),
        ),
    ]
