# Generated by Django 4.1.7 on 2023-03-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('AUTHOR', 'Author'), ('EDITOR', 'Editor'), ('EDITORINCHIEF', 'Editor in Chief')], default='AUTHOR', max_length=30),
        ),
    ]
